### ISSUE TITLE
老哥，请教一下typeOrm的语法问题~

### ISSUE THREAD

**Issue by 2b0x** [kuizuo/kz-admin#4]
没留言功能，只能借助issue来留言了。初次使用orm，想请教下，不知道老哥是否晓得【select aaa,  count(*) as count from xxxx group by aaa】用orm怎么写

我这样写 
await this.xxxxRepository
      .createQueryBuilder(this.xxxxRepository.metadata.tableName)
      .select('aaa')
      .groupBy("aaa")
      .getManyAndCount();
得出来的结果是表的总数

await this.xxxxRepository
      .createQueryBuilder(this.xxxxRepository.metadata.tableName)
      .select('aaa')
      .groupBy("aaa")
      .getRawMany();
这样的话，虽然能分组成功，但是无法得到统计后的分组结果

**Comment by kuizuo** [comment]
你的需求应该是 分组 aaa 字段 并统计每个分组的数量，所以我按照我所理解的需求，回答你的问题。

这在官方文档中 [Getting raw results](https://typeorm.io/select-query-builder#getting-raw-results) 有介绍到，这里我就直接给你正确答案了。

```typescript 
const rawMany = await this.xxxxRepository
      .createQueryBuilder(this.xxxxRepository.metadata.tableName)
      .select('aaa')
      .addSelect('SUM(id)', 'sum')
      .groupBy('aaa')
      .getRawMany();
```

输出 rawMany 可以得到如下结果(演示)

```
[
  RowDataPacket { aaa: '1', sum: 2 },
  RowDataPacket { aaa: '2',', sum: 5 },
  RowDataPacket { aaa: '3', sum: 12 }
]
```

其实如果你不知道如果使用 `createQueryBuilder` 构造出 sql 语句的话，可以直接使用 `this.xxxxRepository.query(sql)` 执行sql语句（不过既然都使用了ORM，就别在手写SQL了）

希望对你有所帮助😪
