### ISSUE TITLE
任务调度功能异常

### ISSUE THREAD

**Issue by charles0122** [kuizuo/kz-admin#5]
我拉下来跑一遍有异常，然后发现线上版本也有异常
Error: Nest could not find EmailJob element this provider does not exist in the current context

**Comment by kuizuo** [comment]
> 我拉下来跑一遍有异常，然后发现线上版本也有异常 Error: Nest could not find EmailJob element this provider does not exist in the current context

这是因为我没有配置邮箱相关参数，你可以在 [.env.development](https://github.com/kuizuo/kz-admin/blob/main/apps/backend/.env.development) 中找到 email 的配置，配置上你的邮箱服务器即可

```
# email
EMAIL_HOST = smtp.qq.com
EMAIL_PORT = 465
EMAIL_USER = your user
EMAIL_PASS = your password
```
