### ISSUE TITLE
前端启动不了

### ISSUE THREAD

**Issue by BlueOrgreen** [kuizuo/kz-admin#6]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/64401491/218774445-69924897-7757-4c52-bd95-4b1ab734cfaa.png">
大佬,你好👋,我后端在kz-admin输入pnpm run start启动成功了, 前端进去到apps/frontend目录下启动后到了登录界面,登录的时候出现proxy错误

**Comment by kuizuo** [comment]
既然都用上了monorepo 那么就无需进入到前端工程(apps/frontend)/后端工程(apps/backend) 在输入一遍pnpm run start这样繁琐启动命令。

在项目的根 package.json 中有以下scripts

```
"scripts": {
    "build": "turbo run build",
    "build:frontend": "turbo run -C frontend build",
    "build:backend": "turbo run -C backend build",
    "test": "turbo run test",
    "lint": "turbo run lint",
    "dev": "turbo run dev",
    "dev:frontend": "turbo run -C frontend dev",
    "dev:backend": "turbo run -C backend dev"
  },
```

你如果想要单独运行前端项目的话就执行pnpm run dev:frontend，同时执行就pnpm run dev。

至于截图的报错信息（5001端口无法访问），大概率是你的后端应用程序没有正常启动，最好检查下apps/backend 下的.env等环境变量是否正确。

当控制台输出如下结果，则说明后端应用准备就绪。
![image](https://user-images.githubusercontent.com/61005888/218862098-2707c105-62e8-454a-8201-1a328982af36.png)

**Comment by BlueOrgreen** [comment]
谢谢大佬🙏🙏




默言忆旧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kuizuo/kz-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 凌晨5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kuizuo/kz-admin] 前端启动不了 (Issue #6)





 
既然都用上了monorepo 那么就无需进入到前端工程(apps/frontend)/后端工程(apps/backend) 在输入一遍pnpm run start这样繁琐启动命令。
 
在项目的根 package.json 中有以下scripts
 "scripts": {     "build": "turbo run build",     "build:frontend": "turbo run -C frontend build",     "build:backend": "turbo run -C backend build",     "test": "turbo run test",     "lint": "turbo run lint",     "dev": "turbo run dev",     "dev:frontend": "turbo run -C frontend dev",     "dev:backend": "turbo run -C backend dev"   },  
你如果想要单独运行前端项目的话就执行pnpm run dev:frontend，同时执行就pnpm run dev。
 
至于截图的报错信息（5001端口无法访问），大概率是你的后端应用程序没有正常启动，最好检查下apps/backend 下的.env等环境变量是否正确。
 
当控制台输出如下结果，则说明后端应用准备就绪。

**Comment by BlueOrgreen** [comment]
愧怍大佬，你好，我尝试模仿你的kuizuo-blog搭建自己的博客；
我遇到一个问题是我在blog目录下想放置文章例如：

但是页面出现的效果很不理想，
这是你的页面效果


想请教大佬有什么思路解决或者我去看哪里的文档？

在百忙之中耽搁大佬时间，实在不好意思。

默言忆旧
***@***.***



&nbsp;
